#!/bin/bash
for((i=0; i<100; i++))
do
  pintos -v -k -T 60 --qemu  --filesys-size=2 -p tests/vm/page-parallel -a page-parallel -p tests/vm/child-linear -a child-linear --swap-size=4 -- -q  -f run page-parallel > trace$i
  grep -nr "exit(0)" trace$i
done

